version: "3.9"
services:
  web:
    build: .
    image: openedc
    container_name: web-${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: ${PORT} ${NAME}
    networks:
      main:
        aliases:
          - web
networks:
  main: